### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by thenirmalprajapati** [ivaaak/.NET-RealEstate#4]
Can you provide me your contact details or you can contact me https://about.me/nirmalprajapati

**Comment by ivaaak** [comment]
Hey, how can I help you?
________________________________
От: Nirmal Prajapati ***@***.***>
Изпратено: 08 април 2023 г. 22:07
До: ivaaak/.NET-RealEstate ***@***.***>
Як: Subscribed ***@***.***>
Тема: [ivaaak/.NET-RealEstate] Contact (Issue #4)

[ВНИМАНИЕ! Подателят е извън Вашата организация. Не отваряйте прикачени файлове и не следвайте публикувани връзки към сайтове, освен ако не сте сигурни, че подателят е доверен и съдържанието е безопасно!]
________________________________

Can you provide me your contact details or you can contact me https://about.me/nirmalprajapati

**Comment by VasTS0** [comment]
Zavyrshih s tova <3
